wormhole-foundation/wormhole-sdk-ts

core/connect/src/tokenTransfer.ts
core/connect/src/types.ts
core/connect/src/wormhole.ts
platforms/evm/__tests__/unit/index.test.ts
platforms/evm/src/chain.ts
platforms/evm/src/platform.ts

make RPC connection implement an interface, dont re-create rpc conn inside each platform method

RPCConnection interface

---

connect/__tests__/index.test.ts
connect/src/config.ts
connect/src/index.ts
connect/src/wormhole.ts
core/definitions/src/platform.ts
core/definitions/src/testing/mocks/chain.ts
core/definitions/src/testing/mocks/platform.ts
package.json
platforms/evm/__tests__/integration/tokenBridge.test.ts
platforms/evm/__tests__/unit/platform.test.ts
platforms/evm/src/platform.ts
platforms/solana/__tests__/integration/tokenBridge.test.ts
platforms/solana/__tests__/unit/platform.test.ts
platforms/solana/src/platform.ts

also making network the primary paramter and allow _overriding_ of conf but default is derived from network

Adding default network from env in connect package

---

connect/src/protocols/gatewayTransfer.ts
connect/src/types.ts
examples/src/cosmos.ts
package-lock.json
platforms/cosmwasm/__tests__/unit/platform.test.ts
platforms/cosmwasm/src/constants.ts
platforms/cosmwasm/src/gateway.ts
platforms/cosmwasm/src/platform.ts
platforms/cosmwasm/src/platformUtils.ts
platforms/cosmwasm/src/protocols/tokenBridge.ts
platforms/cosmwasm/src/unsignedTransaction.ts
platforms/evm/src/platformUtils.ts

fix missing nonce parameter in common payload

---

core/tokenRegistry/src/foreignAssets.ts
core/tokenRegistry/src/types.ts
platforms/solana/src/platformUtils.ts

Before:
After:
Had to put in an artificial sleep to prevent rate limiting but we still get it sometimes, still room for improvement

try to check foreign asset cache concurrently

---

connect/__tests__/index.test.ts
connect/src/protocols/gatewayTransfer.ts
connect/src/protocols/retry.ts
connect/src/protocols/utils.ts
connect/src/wormhole.ts
core/definitions/src/protocols/ibc.ts
examples/src/cosmos.ts
platforms/cosmwasm/src/gateway.ts
platforms/cosmwasm/src/platform.ts
platforms/cosmwasm/src/protocols/ibc.ts

As part of this I changed how getVAABytes takes args to simplify the config for timeouts.
More work is needed to do things like subtract time passed so far from the timeout so subsequent timed requests get the appropriate timeout setting

Cosmos E2E

---

core/base/__tests__/finality.ts
core/base/src/constants/contracts/index.ts
core/base/src/constants/contracts/rollupCheckpoint.ts
core/base/src/constants/finality.ts
core/definitions/src/types.ts

for #94 
How should we take into account the L2/L1 stuff?
https://www.notion.so/Finality-in-Wormhole-78ffa423abd44b7cbe38483a16040d83#c03222487c11432e80bfa31a574f8dd3

Start to add finality settings

---

core/definitions/src/attestation.ts
core/definitions/src/chain.ts
core/definitions/src/platform.ts
core/definitions/src/protocol.ts
core/definitions/src/protocols/core.ts
core/definitions/src/testing/mocks/platform.ts
examples/src/helpers/helpers.ts
platforms/aptos/src/address.ts
platforms/aptos/src/platform.ts
platforms/cosmwasm/src/platform.ts
platforms/evm/src/platform.ts
platforms/solana/src/platform.ts

make it easier to access a static reference to the class instance

reduce some boilerplate

---

connect/src/protocols/tokenTransfer.ts
core/base/src/utils/encoding.ts
examples/package.json
examples/src/algoTokenBridge.ts
examples/src/createWrapped.ts
package-lock.json
platforms/algorand/package.json
platforms/algorand/protocols/core/package.json
platforms/algorand/protocols/tokenBridge/package.json
platforms/algorand/protocols/tokenBridge/src/tokenBridge.ts
platforms/algorand/src/address.ts
platforms/algorand/src/testing/signer.ts
platforms/algorand/src/utilities.ts
platforms/solana/protocols/tokenBridge/src/tokenBridge.ts

See example testing notes at algoTokenBridge.ts Line 25

Refactor-algorand-sr

---

connect/package.json
core/base/package.json
core/definitions/package.json
examples/package.json
package.json
platforms/algorand/package.json
platforms/algorand/protocols/core/package.json
platforms/algorand/protocols/tokenBridge/package.json
platforms/aptos/package.json
platforms/aptos/protocols/core/package.json
platforms/aptos/protocols/tokenBridge/package.json
platforms/cosmwasm/package.json
platforms/cosmwasm/protocols/core/package.json
platforms/cosmwasm/protocols/ibc/package.json
platforms/cosmwasm/protocols/tokenBridge/package.json
platforms/evm/package.json
platforms/evm/protocols/cctp/package.json
platforms/evm/protocols/core/package.json
platforms/evm/protocols/tokenBridge/package.json
platforms/solana/package.json
platforms/solana/protocols/cctp/package.json
platforms/solana/protocols/core/package.json
platforms/solana/protocols/tokenBridge/package.json
tokenRegistry/package.json

This is breaking publish with npm 10 :-)

Unglob the files config

---

connect/src/routes/route.ts
connect/src/routes/tokenBridge/automatic.ts
connect/src/routes/tokenBridge/manual.ts

make implementation details implementation details again

normalizedParams are not mandatory

---

core/base/src/constants/index.ts
core/base/src/constants/tokens/index.ts
core/base/src/constants/tokens/mainnet.ts
core/base/src/constants/tokens/mainnetDetails.ts
core/base/src/constants/tokens/testnet.ts
core/base/src/constants/tokens/testnetDetails.ts
core/base/src/constants/tokens/types.ts
core/definitions/src/chain.ts
core/definitions/src/types.ts
package-lock.json
package.json
tokenRegistry/package.json
tokenRegistry/src/scripts/importConnect.ts

We need to look up token details a bunch and we want to avoid RPC calls.
Providing this in config is important as well for downstream users

Tokens: Add token cache

---

connect/src/routes/request.ts
connect/src/routes/tokenBridge/automatic.ts

Logic is ported from https://github.com/wormhole-foundation/wormhole-connect/blob/development/wormhole-connect/src/routes/relay/relay.ts#L277-L284

Implement min amount check for automatic token bridge

---

core/base/__tests__/tokens.ts
core/base/src/constants/tokens/index.ts
core/base/src/constants/tokens/mainnet.ts
core/base/src/constants/tokens/testnet.ts
core/base/src/constants/tokens/types.ts
core/definitions/src/chain.ts
core/definitions/src/types.ts
tokenRegistry/src/scripts/importConnect.ts

Remove chain name from the token row
Fix wrapped address to properly denote that its a symbol

TokenList: Trim extra details, fix incorrect field

---

connect/src/index.ts
connect/src/protocols/cctpTransfer.ts
connect/src/protocols/gatewayTransfer.ts
connect/src/protocols/tokenTransfer.ts
connect/src/protocols/wormholeTransfer.ts
connect/src/routes/index.ts
connect/src/routes/request.ts
connect/src/routes/route.ts
connect/src/routes/tokenBridge/automatic.ts
connect/src/routes/tokenBridge/manual.ts
connect/src/routes/types.ts
connect/src/types.ts
core/base/src/constants/tokens/mainnetDetails.ts
core/base/src/constants/tokens/testnetDetails.ts
core/base/src/constants/tokens/types.ts
core/definitions/src/attestation.ts
examples/src/createWrapped.ts
examples/src/helpers/helpers.ts
examples/src/router.ts
tokenRegistry/src/scripts/importConnect.ts

Improve typing on generic route params

Routes: define interface for generic params

---

core/base/src/constants/explorer.ts
core/base/src/constants/finality.ts
core/base/src/constants/rpc.ts

reference: https://evmdocs.acala.network/network/network-configuration

add karura and acala configs

---

connect/src/common.ts
connect/src/protocols/cctpTransfer.ts
connect/src/protocols/gatewayTransfer.ts
connect/src/protocols/tokenTransfer.ts
connect/src/protocols/wormholeTransfer.ts
connect/src/wormhole.ts
core/base/src/constants/platforms.ts
core/definitions/src/chain.ts
core/definitions/src/platform.ts
core/definitions/src/testing/mocks/chain.ts
core/definitions/src/testing/mocks/platform.ts
platforms/algorand/src/chain.ts
platforms/algorand/src/platform.ts
platforms/aptos/src/chain.ts
platforms/cosmwasm/src/chain.ts
platforms/cosmwasm/src/gateway.ts
platforms/cosmwasm/src/platform.ts
platforms/evm/src/chain.ts
platforms/evm/src/platform.ts
platforms/solana/src/chain.ts
platforms/solana/src/platform.ts

ChainContext: Reorder chain context generic template parameters to ease integration

ChainContext: Reorder chain context generic template parameters

---

core/base/src/constants/tokens/mainnet.ts
core/base/src/constants/tokens/mainnetDetails.ts
core/definitions/src/chain.ts

Fix decimal lookup

---

core/base/src/constants/contracts/tokenBridge.ts

looks like a pasta error from optimism sepolia

update base sepolia token bridge address

---

core/base/src/constants/finality.ts

https://www.notion.so/wormholefoundation/Finality-in-Wormhole-78ffa423abd44b7cbe38483a16040d83#25a9d676ea9f44efade33eeacff31ba8

add more finality thresholds

---

core/definitions/src/index.ts
core/definitions/src/payloads/ntt.ts
core/definitions/src/protocols/ntt.ts

https://github.com/wormhole-foundation/wormhole-connect/pull/1674/files#diff-1623579a08d6129c31d79aa36cfb6560946f1601d9c97406ca1a6c0923a97e82

NTT: Start to add ntt protocol definition

---

platforms/algorand/protocols/core/package.json
platforms/algorand/protocols/tokenBridge/package.json
platforms/aptos/protocols/core/package.json
platforms/aptos/protocols/tokenBridge/package.json
platforms/aptos/src/index.ts
platforms/sui/protocols/core/package.json
platforms/sui/protocols/tokenBridge/package.json

I think this should fix webpack issues with protocols not being registered
also export aptos signer

Add sideEffects field to package.json

---

core/definitions/src/payloads/ntt.ts

change sequence to id in nttManager payload (reflect PR228)

---

explicitExport.ts

Adding this in a stand-alone pr to get it merged without the export changes

Misc: Add explicit export script

---

README.md

Fix link to TS docs

---

core/base/src/utils/layout/utils.ts

see the latest [ntt payload change PR](https://github.com/wormhole-foundation/wormhole-sdk-ts/pull/419) to see what this PR fixes

fix customizableBytes fixed and custom conversion type deduction

---

platforms/solana/src/signer.ts

code stolen from wormhole-connect, thanks @artursapek and @kev1n-peters

Solana: Priority Fee improvements

---

platforms/algorand/package.json
platforms/algorand/protocols/core/package.json
platforms/algorand/protocols/tokenBridge/package.json
platforms/aptos/package.json
platforms/aptos/protocols/core/package.json
platforms/aptos/protocols/tokenBridge/package.json
platforms/cosmwasm/package.json
platforms/cosmwasm/protocols/core/package.json
platforms/cosmwasm/protocols/ibc/package.json
platforms/cosmwasm/protocols/tokenBridge/package.json
platforms/evm/package.json
platforms/evm/protocols/cctp/package.json
platforms/evm/protocols/core/package.json
platforms/evm/protocols/portico/package.json
platforms/evm/protocols/tokenBridge/package.json
platforms/solana/package.json
platforms/solana/protocols/cctp/package.json
platforms/solana/protocols/core/package.json
platforms/solana/protocols/tokenBridge/package.json
platforms/sui/package.json
platforms/sui/protocols/core/package.json
platforms/sui/protocols/tokenBridge/package.json

Specify built file that contains side effects explicitly

Side effects for effecting sides

---

depcheck.sh
examples/package.json
package-lock.json
platforms/algorand/package.json
platforms/algorand/src/address.ts
platforms/aptos/package.json
platforms/aptos/protocols/core/package.json
platforms/aptos/protocols/tokenBridge/package.json
platforms/cosmwasm/package.json
platforms/cosmwasm/protocols/core/package.json
platforms/cosmwasm/protocols/tokenBridge/package.json
platforms/cosmwasm/src/address.ts
platforms/cosmwasm/src/gateway.ts
platforms/cosmwasm/src/signer.ts
platforms/cosmwasm/src/types.ts
platforms/evm/package.json
platforms/evm/protocols/cctp/package.json
platforms/evm/protocols/core/package.json
platforms/evm/protocols/portico/package.json
platforms/evm/protocols/tokenBridge/package.json
platforms/evm/src/address.ts
platforms/solana/package.json
platforms/solana/protocols/cctp/package.json
platforms/solana/protocols/core/package.json
platforms/solana/protocols/tokenBridge/package.json
platforms/sui/package.json
sdk/package.json
sdk/src/addresses.ts
tsconfig.cjs.json

Using https://github.com/barnjamin/ezui to build/test bundle sizes
Import full cosmwasm package to get the Address
Import from `/address` conditional export path (note, only major change is # of packages considered)
After _also_ removing the platform import from the source `address.ts` file
No import of cosmwasm

Packaging: Experiment with conditional exports

---

connect/package.json
core/base/package.json
core/definitions/package.json
examples/package.json
package.json
platforms/algorand/package.json
platforms/algorand/protocols/core/package.json
platforms/algorand/protocols/tokenBridge/package.json
platforms/aptos/package.json
platforms/aptos/protocols/core/package.json
platforms/aptos/protocols/tokenBridge/package.json
platforms/cosmwasm/package.json
platforms/cosmwasm/protocols/core/package.json
platforms/cosmwasm/protocols/ibc/package.json
platforms/cosmwasm/protocols/tokenBridge/package.json
platforms/evm/package.json
platforms/evm/protocols/cctp/package.json
platforms/evm/protocols/core/package.json
platforms/evm/protocols/portico/package.json
platforms/evm/protocols/tokenBridge/package.json
platforms/solana/package.json
platforms/solana/protocols/cctp/package.json
platforms/solana/protocols/core/package.json
platforms/solana/protocols/tokenBridge/package.json
platforms/sui/package.json
platforms/sui/protocols/core/package.json
platforms/sui/protocols/tokenBridge/package.json
sdk/package.json

do we actually have to do this every time? can the action do it?

Package: bump version to match latest release

---

core/base/src/constants/chains.ts
core/base/src/constants/contracts/core.ts
core/base/src/constants/contracts/tokenBridge.ts
core/base/src/constants/nativeChainIds.ts
core/base/src/constants/platforms.ts
core/base/src/constants/rpc.ts
core/definitions/src/types.ts

Also change how native chain ids are specified and modify typing to work with the new layout

Consts: Add Blast

---

core/definitions/__tests__/mockGuardian.ts
core/definitions/src/protocols/core/core.ts
core/definitions/src/protocols/core/index.ts
core/definitions/src/signature.ts
core/definitions/src/testing/mocks/guardian.ts
examples/src/repairVaa.ts
package-lock.json
platforms/algorand/protocols/core/src/core.ts
platforms/aptos/protocols/core/src/core.ts
platforms/cosmwasm/protocols/core/src/core.ts
platforms/evm/protocols/core/src/core.ts
platforms/solana/protocols/core/src/core.ts
platforms/sui/protocols/core/src/core.ts

Add repair VAA script and methods to support it

Guardian Set utils

---

core/definitions/src/chain.ts

Add check for contracts and skip cache set if they are passed

---

package-lock.json
platforms/solana/package.json
platforms/solana/protocols/cctp/package.json
platforms/solana/protocols/core/package.json
platforms/solana/protocols/tokenBridge/package.json

partially addresses #480 
remaining is axios xss thru injective but the latest beta still has the 0.27.2 version in deps https://github.com/InjectiveLabs/injective-ts/blob/dev/packages/sdk-ts/package.json#L55

Packaging: Update several deps 

---

platforms/solana/protocols/core/src/core.ts

Also remove the condition negation since it'd filter out the ixs it intends to capture

Add missing return in SolanaWormholeCore parseSequenceFromLog

---

platforms/algorand/src/signer.ts
platforms/aptos/src/signer.ts
platforms/cosmwasm/src/signer.ts
platforms/evm/src/signer.ts
platforms/solana/src/signer.ts
platforms/sui/src/signer.ts

puts the console log from every signer about what is being signed behind the debug flag

Signers: put console.log behind debug flag

---

platforms/aptos/protocols/tokenBridge/src/tokenBridge.ts
platforms/sui/protocols/tokenBridge/src/tokenBridge.ts

https://github.com/wormhole-foundation/wormhole/blob/6294969ecf1420e18c6f8575db4477aa3b39aadb/sdk/js/src/token_bridge/getIsTransferCompleted.ts#L237
https://github.com/wormhole-foundation/wormhole/blob/6294969ecf1420e18c6f8575db4477aa3b39aadb/sdk/js/src/token_bridge/getIsTransferCompleted.ts#L267

fix isTransferCompleted (sui, aptos)

---

platforms/solana/protocols/core/src/utils/program.ts
platforms/solana/protocols/tokenBridge/src/utils/tokenBridge/program.ts

Solana: Remove type assertion on import

---

connect/src/routes/resolver.ts
examples/src/router.ts

Also remove console.error for route selection

Examples: Update router example

---

platforms/evm/protocols/cctp/src/circleBridge.ts

BugFix: Circle domain check incorrect

---

platforms/cosmwasm/src/constants.ts

from https://github.com/cryptocrew-validators/cc-reports/tree/main/ibc-wormhole-testnet#channel-list

Add new ibc channels

---

core/base/__tests__/layout.ts
core/base/src/utils/layout/discriminate.ts

proper fixes for the issue discovered in #559:
* replaced `(1 << (8 * lengthSize)) - 1` which apparently uses an int32 under the hood and silently overflows with `2**(8 * lengthSize) - 1`
* add missing `!== null` check for `offset` to correctly handle cases where `offset == 0`
* added missing `++bytesPos` when determining shared fixed bytes for switch layouts (which also caused an infinite loop)

fix three bugs in discriminate and clean up

---

examples/src/helpers/helpers.ts
platforms/evm/src/signer.ts

Evm: add additional overrides to evm signer for better gas settings

---

core/definitions/src/universalAddress.ts
platforms/evm/src/address.ts
platforms/sui/protocols/tokenBridge/src/tokenBridge.ts

Sui: Bugfix for original asset address type

---

platforms/sui/protocols/core/src/index.ts
platforms/sui/protocols/tokenBridge/src/index.ts
platforms/sui/src/address.ts

- Fix SUI registration bug
- Fix SUI address return type

Fixes for connect

---

core/base/src/utils/array.ts
core/base/src/utils/layout/items.ts
core/base/src/utils/layout/layout.ts
core/base/src/utils/mapping.ts
core/definitions/__tests__/governanceVaa.ts
core/definitions/src/layout-items/chain.ts
core/definitions/src/layout-items/string.ts
core/definitions/src/protocols/governance/globalAccountant.ts
core/definitions/src/protocols/governance/layout.ts
platforms/solana/protocols/core/src/utils/instructions/governance.ts
platforms/solana/protocols/tokenBridge/src/utils/tokenBridge/instructions/governance.ts

* implement enum item
* condense governance VAA specification code
* introduce actionArgs grouping in governance VAAs (see [alt branch](https://github.com/wormhole-foundation/wormhole-sdk-ts/tree/missing-governance-layouts-alt) that retains previous structure)

Missing governance layouts contrib

---

core/base/src/constants/chains.ts
core/base/src/constants/circle.ts
core/base/src/constants/nativeChainIds.ts
core/base/src/utils/array.ts
core/base/src/utils/encoding.ts
core/base/src/utils/layout/deserialize.ts
core/base/src/utils/layout/layout.ts
core/base/src/utils/layout/serialize.ts
core/base/src/utils/mapping.ts
core/base/src/utils/metaprogramming.ts

* fixed constMap.get params and return type
* implemented constMap.subMap
* fixed a few things here and there

fix constMap get and impl subMap feature

---

connect/src/protocols/tokenBridge/tokenTransfer.ts
platforms/aptos/src/address.ts
platforms/evm/protocols/tokenBridge/src/tokenBridge.ts

- hash aptos token addresses with sha3_256 for token bridge
- fix WETH check - only do it if the token is from the destination chain (and therefore guaranteed to be EVM and unwrappable WETH)

bug fixies

---

README.md

ran `npm run examples` to update the README.md based on adjusted examples

update root readme based on adjusted example files

---

connect/src/routes/tokenBridge/automatic.ts

The max swap amount should be the input amount if it's lower than the max swap amount returned by the destination relayer contract.

connect: auto tb gas dropoff max amount fix

---

connect/src/protocols/cctp/cctpTransfer.ts
connect/src/protocols/tokenBridge/tokenTransfer.ts
connect/src/routes/portico/automatic.ts
connect/src/routes/request.ts
connect/src/routes/types.ts
connect/src/types.ts
core/base/src/constants/finality.ts

The eta tells us the estimated transfer time in milliseconds (essentially finality time).

connect: Added eta to quote interface

---

connect/src/routes/route.ts

Needed for NTT for resuming inbound queued transfers.

connect: added resume method to FinalizableRoute

---

platforms/solana/src/signer.ts

We were not resolving the address lookup table accounts

solana: fix determinePriorityFee method for VersionedTransactions

---

.github/workflows/build.yml
core/base/__tests__/finality.ts

running into this issue: https://github.com/jestjs/jest/issues/11617

tests: fix finality tests, run CI tests on pull requests

---

README.md

A little README grooming

---

platforms/sui/__tests__/unit/address.test.ts
platforms/sui/src/address.ts

sui: getCoinType native token address fix

---

core/base/src/constants/finality.ts

Consistent with Ethereum finality (72)

sepolia finality should be 72

---

core/base/src/constants/contracts/core.ts
core/base/src/constants/contracts/tokenBridge.ts
core/base/src/constants/finality.ts
core/base/src/constants/nativeChainIds.ts
core/base/src/constants/rpc.ts

The core is available [here](https://seitrace.com/address/0xBB73cB66C26740F31d1FabDC6b7A46a038A300dd?chain=atlantic-2).
The token bridge is available [here](https://seitrace.com/address/0x23908A62110e21C04F3A4e011d24F901F911744A?chain=atlantic-2).

Seievm Support

---

core/base/__tests__/mapping.ts
core/base/src/utils/mapping.ts

also fix incorrect tests (constMap requires data to be rectangular)

fix incorrect constmap submap implementation

---

connect/src/protocols/tokenBridge/tokenTransfer.ts

Set the quote source token to the input token

TB route: source token quote fix

---

platforms/aptos/src/platform.ts

This code was making a single graphql call for each individual token balance... and getting rate limited to hell (as it should be)

Use graphql correctly for fetching bulk balances

---

core/base/src/constants/circle.ts

https://developers.circle.com/stablecoins/usdc-contract-addresses#mainnet
https://worldscan.org/address/0x79A02482A880bCe3F13E09da970dC34dB4cD24D1

added worldchain mainnet usdc address

---

core/base/src/constants/finality.ts

https://docs.sei.io/evm 400ms block time

fix: Add SeiEVM block time

---

platforms/evm/protocols/tokenBridge/src/executorTokenBridge.ts

As discussed internally, we are updating gas limits for token bridge.

fix: Update token bridge gas limits

---

connect/src/routes/types.ts

Useful for UI to show recovery link when relay fails

feat: add explorer url to RelayFailedError

---

core/base/src/constants/nativeChainIds.ts

chainid from here: https://chainlist.org/chain/102030

add creditcoin chainid

---

core/base/src/constants/dai.ts
core/base/src/constants/index.ts
core/base/src/constants/usds.ts
core/base/src/constants/usdt.ts

Avoids copying these addresses across multiple repos...

feat: add stablecoin addresses
