wormhole-foundation/wormhole-sdk-ts

- .gitignore
- packages/aptos/src/context.ts
- packages/evm/src/context.ts
- packages/sdk-core/src/abstracts/tokenBridge.ts
- packages/sdk-core/src/wormhole.ts
- packages/sei/src/context.ts
- packages/solana/src/context.ts
- packages/sui/src/context.ts
Every context had some check to see if the transfer was meant for Solana since it requires a different receiver address than the main account.
This pr adds a `getRecipientAddress` to the RelayerAbstract class with the default implementation of returning the same address. Currently only `SolanaContext` overrides this method to provide the ATA address
> Cleanup: Add getRecipientAddress to RelayerAbstract

- packages/sdk-core/src/utils/vaa/tokenBridge.ts
Trying to call this on a solana tx results in 🤮 
BigInt will allow hex representation if you give it the hint of `0x` prefix
> pass a hex string to BigInt so it parses correctly

- connect/__tests__/index.test.ts
- connect/src/constants.ts
- connect/src/wormhole.ts
- core/definitions/src/chain.ts
- core/definitions/src/platform.ts
- core/definitions/src/protocols/cctp.ts
- core/definitions/src/protocols/core.ts
- core/definitions/src/protocols/tokenBridge.ts
- core/definitions/src/rpc.ts
- core/definitions/src/testing/mocks/platform.ts
- package.json
- platforms/evm/__tests__/integration/tokenBridge.test.ts
- platforms/evm/__tests__/unit/platform.test.ts
- platforms/evm/src/platform.ts
- platforms/solana/__tests__/integration/tokenBridge.test.ts
- platforms/solana/__tests__/unit/platform.test.ts
- platforms/solana/src/chain.ts
- platforms/solana/src/platform.ts
The current relationship between `Platform` and `ChainContext` is, in a word, bad.
This PR:
1) Changes `Platform` implementations from a class to a `module` that exports methods and values. 
2) Moves protocol client accessors (e.g. `getTokenBridge`) to their own interfaces with type guard methods
3) Modifies `ChainContext` now provides methods to check if the protocol is supported prior to trying to get them
The benefit is better structure and the ability to call platform specific methods without creating a new instance of a class and better handling of protocol support.
It also makes the Platform itself a sort of singleton who's config is updated across the runtime if modified. 
The downside is that it may be a strange pattern so the `MockPlatform` is still a class (that implements the …
> Make platforms modules

- core/definitions/src/chain.ts
- core/definitions/src/testing/mocks/chain.ts
- core/definitions/src/testing/mocks/platform.ts
- platforms/evm/src/chain.ts
- platforms/evm/src/platform.ts
- platforms/solana/src/chain.ts
- platforms/solana/src/platform.ts
This changes the ChainContext constructor to avoid passing in the module like a value.
Instead, since we're relying on the platform and we know what platform we want to use, we provide it in the concrete implementation.
> Hardcode platform in ChainContext

- platforms/evm/src/constants.ts
https://chainlist.org/?search=gnosis&testnets=true
> Fix gnosis testnet chain id

- connect/__tests__/index.test.ts
- connect/__tests__/mocks/publicrpc.ts
- connect/src/wormhole.ts
- Uses signed_vaa endpoint, which is also available in wormholescan.
- Adds options to set timeouts.
> use signed_vaa endpoint on getVaaBytes

- examples/src/helpers/helpers.ts
- platforms/solana/__tests__/integration/tokenBridge.test.ts
- platforms/solana/protocols/cctp/src/circleBridge.ts
- platforms/solana/protocols/core/src/core.ts
- platforms/solana/protocols/tokenBridge/src/automaticTokenBridge.ts
- platforms/solana/protocols/tokenBridge/src/tokenBridge.ts
- platforms/solana/src/platform.ts
- platforms/solana/src/testing/debug.ts
- platforms/solana/src/testing/index.ts
- platforms/solana/src/testing/sendSigner.ts
- platforms/solana/src/testing/signer.ts
- platforms/solana/src/unsignedTransaction.ts
Solana transaction changes to make it possible to resubmit a tx
This requires us to pass not only the transaction but all the ephemeral keypairs used to sign the transactions so that the transaction may be updated with a more recent blockhash and re-signed and sent.
> Solana: Provide ability to resign transactions with ephemeral keys

- connect/src/protocols/cctpTransfer.ts
- connect/src/protocols/tokenTransfer.ts
- connect/src/wormholeTransfer.ts
This change makes the TransferReceipt code a little more verbose but a lot more legible. And the compile-time checks seems stricter now, because `TransferState` is only kept in one place. So that's nice.
> Use union types for TransferReceipt

- connect/src/protocols/cctpTransfer.ts
- connect/src/protocols/tokenTransfer.ts
By allowing the dev to set from/to chain contexts on the Transfer obj, we can be sure we're using the same rpc connection as well as whatever other overrides they've decided to apply.
> WormholeTransfer: Add chain contexts to transfer obj

- platforms/algorand/protocols/tokenBridge/src/tokenBridge.ts
The opt in to the asset needs to happen _after_ the payment to cover the opt in
> Algorand: make the opt in happen after the payment

- core/base/src/constants/nativeChainIds.ts
Holesky is currently defined with Optimism Sepolia's native chain id, blocking either network from being used:
`Error: Platform Evm has multiple chains with native chain id 11155420`
Grabbed chainId from https://github.com/eth-clients/holesky
> fix: holesky chainId

- README.md
Code snippets were deprecated in the readme, tested with the SDK version ```0.3.0``` and updated
> Updated Code Snippets

- core/definitions/src/address.ts
- core/definitions/src/payloads/automaticCircleBridge.ts
- core/definitions/src/payloads/automaticTokenBridge.ts
- core/definitions/src/payloads/bam.ts
- core/definitions/src/payloads/circleBridge.ts
- core/definitions/src/payloads/governance.ts
- core/definitions/src/payloads/portico.ts
- core/definitions/src/payloads/relayer.ts
- core/definitions/src/payloads/tokenBridge.ts
- core/definitions/src/protocol.ts
- core/definitions/src/protocols/circleBridge.ts
- core/definitions/src/protocols/core.ts
- core/definitions/src/protocols/ibc.ts
- core/definitions/src/protocols/nftBridge.ts
- core/definitions/src/protocols/portico.ts
- core/definitions/src/protocols/relayer.ts
- core/definitions/src/protocols/tokenBridge.ts
- core/definitions/src/vaa/registration.ts
- platforms/algorand/src/address.ts
- platforms/aptos/src/address.ts
- platforms/cosmwasm/src/address.ts
- platforms/evm/src/address.ts
- platforms/solana/src/address.ts
I suspect this is the cause of certain errors around unregistered native addresses. 
Since we always import `Wormhole` but never `WormholeNamespace`, I _think_ the native addresses were never seen as registered/available
> Change WormholeNamespace back to Wormhole

- connect/src/protocols/cctpTransfer.ts
- connect/src/protocols/gatewayTransfer.ts
- core/base/__tests__/layout.ts
- core/base/src/utils/layout/deserialize.ts
- core/base/src/utils/layout/discriminate.ts
- core/base/src/utils/layout/fixedDynamic.ts
- core/base/src/utils/layout/index.ts
- core/base/src/utils/layout/items.ts
- core/base/src/utils/layout/layout.ts
- core/base/src/utils/layout/serialize.ts
- core/base/src/utils/layout/size.ts
- core/base/src/utils/layout/utils.ts
- core/base/src/utils/mapping.ts
- core/base/src/utils/metaprogramming.ts
- core/definitions/src/layout-items/signature.ts
- core/definitions/src/layout-items/universalAddress.ts
- core/definitions/src/payloads/automaticCircleBridge.ts
- core/definitions/src/payloads/automaticTokenBridge.ts
- core/definitions/src/payloads/bam.ts
- core/definitions/src/payloads/circleBridge.ts
- core/definitions/src/payloads/ntt.ts
- core/definitions/src/payloads/portico.ts
- core/definitions/src/payloads/relayer.ts
- core/definitions/src/payloads/tokenBridge.ts
- core/definitions/src/signature.ts
- core/definitions/src/vaa/create.ts
- core/definitions/src/vaa/functions.ts
- platforms/cosmwasm/src/address.ts
killed ObjectLayout item and instead moved its abilities to custom field of BytesLayout item
BytesLayoutItems can now enforce a size or a lengthSize while also natively supporting custom layouts (instead of having to wrap the layout in a CustomConversion and hence losing discrimination power, etc.)
implemented new custom payload mechanism for all payloads that have user definable payloads
also implemented NTT payloads
> Ntt payloads and better custom payload specification mechanism

- sdk/src/index.ts
Fixes type inference for the `Wormhole` obj generic parameter.
Without this, `wormhole("Testnet", ...)` is inferred to `Wormhole<"Mainnet"|"Testnet"|"Devnet">`
with this, its properly set to `Wormhole<"Testnet">`
> fix type inference for wormhole loader

- connect/package.json
- core/base/package.json
- core/definitions/package.json
- platforms/algorand/package.json
- platforms/algorand/protocols/core/package.json
- platforms/algorand/protocols/tokenBridge/package.json
- platforms/aptos/package.json
- platforms/aptos/protocols/core/package.json
- platforms/aptos/protocols/tokenBridge/package.json
- platforms/cosmwasm/package.json
- platforms/cosmwasm/protocols/core/package.json
- platforms/cosmwasm/protocols/ibc/package.json
- platforms/cosmwasm/protocols/tokenBridge/package.json
- platforms/evm/package.json
- platforms/evm/protocols/cctp/package.json
- platforms/evm/protocols/core/package.json
- platforms/evm/protocols/portico/package.json
- platforms/evm/protocols/tokenBridge/package.json
- platforms/solana/package.json
- platforms/solana/protocols/cctp/package.json
- platforms/solana/protocols/core/package.json
- platforms/solana/protocols/tokenBridge/package.json
- platforms/sui/package.json
- platforms/sui/protocols/core/package.json
- platforms/sui/protocols/tokenBridge/package.json
- sdk/package.json
_strange_
without this change next complains about module resolution
with this change, its resolved properly
notably changing `moduleResolution` in `tsconfig.json` from default of `bundler` to `Node16` allowed resolution to happen
linking for https://github.com/vercel/next.js/issues/39375
> Bug: default must be last

- connect/src/config.ts
- connect/src/wormhole.ts
- examples/src/config.ts
- examples/src/router.ts
- sdk/src/index.ts
While debugging #431, I found that the intended method of providing tokens to the partial config overrides would fail while trying to set properties on an undefined object.
This provides a default empty object for the `base` value if its not set and properly sets the Network generic param on the Config type
> Fix partial config issue with token map

- core/definitions/src/chain.ts
- core/definitions/src/contracts.ts
Calling `getProtocol` on an instance of a chain should provide a way to pass contract overrides or additional contracts that are not part of the default set.
Without this change, its necessary to get the protocol initializer from the platform _then_ init it with the contracts + overrides
https://github.com/wormhole-foundation/example-native-token-transfers/blob/barnji/ts-sdk/sdk/__tests__/utils.ts#L199-L206
> Definitions: Allow contracts to be passed to the `getProtocol` fn

- sdk/src/index.ts
This extra import ensures the addresses of all platforms are registered and available to the runtime if anything is imported, no need to remember an extra import to parse addresses
> SDK: Export addresses from index

- connect/src/protocols/cctpTransfer.ts
- connect/src/protocols/tokenTransfer.ts
- connect/src/routes/route.ts
- connect/src/types.ts
- core/definitions/src/attestation.ts
A redeemed state should be defined and set in the case the transfer has been delivered/redeemed but not seen to be finalized yet
> Connect: Transfer State updates

- platforms/cosmwasm/protocols/core/package.json
- platforms/cosmwasm/protocols/ibc/package.json
- platforms/cosmwasm/protocols/tokenBridge/package.json
- platforms/solana/protocols/core/src/utils/instructions/verifySignature.ts
- platforms/sui/protocols/core/package.json
- platforms/sui/protocols/tokenBridge/package.json
This should hopefully resolve errors I've been getting when trying to use this SDK in Connect. Both `@mysten/sui.js` and `@injectivelabs/sdk-ts` were resolving to the wrong version.
> Add missing dependencies to protocol pkgs

- core/definitions/src/chain.ts
- core/definitions/src/protocol.ts
In order to support Protocol clients that may have versioned bindings, a new type is added that signals it can be invoked to fetch the version.
This is the first place in the SDK we're doing this and its meant to support the different bindings a given Ntt contract may require.
Without this change the only way to get the version checked (through "normal" use) is by first setting the config in base (that means 1 copy of `ntt` possible)
then calling:
```ts
chain.getProtocol("Ntt", undefined, await chain.getRpc())
```
which causes the `fromRpc` method on the protocol initializer to fire and fetch the version from the contract on-chain.
> Protocols: Add `VersionedProtocolInitializer`

- core/definitions/src/testing/mocks/guardian.ts
We no longer construct the VAA from scratch as is done in the original implementation so we need to check for and set the guardian set index or error if we get a VAA with one we're not expecting
> add guardian set index to mock guardian signer

- core/base/src/constants/circle.ts
I'm struggling to use CCTP through SDK where src chain is Optimism because of this error on `xfer.initiateTransfer()`
> could not decode result data (value="0x", info={ "method": "allowance", "signature": "allowance(address,address)" }, code=BAD_DATA, version=6.9.1
It seems the OP usdc address is not correct, there is nothing deployed on [0x179522635726710dd7d2035a81d856de4aa7836c](https://optimistic.etherscan.io/address/0x179522635726710dd7d2035a81d856de4aa7836c)
> Update USDC contract address on OP

- examples/src/helpers/helpers.ts
- platforms/solana/src/signer.ts
My reasoning for the `percentileMultiple` config setting was that the percentile thing is
1) limited to only whatever happened in the recent transactions
2) may be impacted by insanely high values
If you're having trouble landing txs and you max it to 1.0, the highest fee paid wins (oof maybe)
I think it should be possible to set the value to 50th percentile but also apply a 2 or 3x multiple to that so you can
1) be (more) confident the value you plucked from recent is within a normal-ish bound
2) juice it to move to the front of the list
> Solana: Refactor Solana signer, Add config options

- connect/src/routes/tokenBridge/automatic.ts
- connect/src/routes/tokenBridge/manual.ts
prevents a throw that happens [here](https://github.com/wormhole-foundation/wormhole-sdk-ts/blob/main/platforms/evm/protocols/tokenBridge/src/tokenBridge.ts#L94) from crashing routes
really this should return something like a `Result` with either `Some(token)` or `None` instead of throwing... but this will do for now :-)
> don't throw in token bridge lookup

- connect/src/routes/resolver.ts
- connect/src/routes/route.ts
This is required for proper typing in Connect SDKv2 migration 🤓
> Expose generic types on RouteConstructor

- platforms/solana/src/platform.ts
- platforms/solana/src/signer.ts
Implements the suggestions from here: https://docs.triton.one/chains/solana/sending-txs
> solana: Added client-side tx rebroadcast logic

- core/base/src/constants/nativeChainIds.ts
- core/definitions/src/protocols/relayer/relayerLayout.ts
- platforms/solana/__tests__/integration/tokenBridge.test.ts
- platforms/solana/jest.config.ts
This PR changes the layout for the `RedeliveryInstruction` of the Standard Relayers from `vaaKeyLayout` directly to `messageKeySwitchLayout`, because if trying to deserialize with vaaKeyLayout directly, it tries to read the first bytes as a chain instead of as a payload type
> Fix relayer redelivery layout

- core/definitions/src/vaa/functions.ts
If a chain id is created but not yet available in the SDK, the `deserialize` function with throw because the `emitterChain` is checked against the known list of chains.
This fn provides a way to get the data parsed out of the VAA without doing a check on the chain id
> Layouts: Provide function to parse VAA with unknown chain id

- connect/src/protocols/tokenBridge/tokenTransfer.ts
Previously we would never set the receipt state to `DestinationFinalized` when the receipt was in the `DestinationInitiated` state. The case that sets the `DestinationFinalized` state should also check both `isAttested` and `isRedeemed`.
> protocols/tokenBridge: check xfer complete when in isRedeemed state

- connect/src/protocols/cctp/cctpTransfer.ts
- connect/src/protocols/tokenBridge/tokenTransfer.ts
- connect/src/routes/cctp/manual.ts
- connect/src/routes/route.ts
- connect/src/routes/tokenBridge/manual.ts
This adds a required `resume` method to `ManualRoute`, which takes a `TransactionId` (combination of chain + hash) and returns a `Receipt`.
> Manual resume

- connect/src/protocols/cctp/cctpTransfer.ts
This function tries to determine whether a CCTP transfer uses a Wormhole or Circle attestation, but there is an error thrown downstream that indicates it's not a Wormhole attestation which this function just propagates. This diff catches that error and lets `msgIds` remain empty so the rest of the function works.
> Swallow Circle attestation error

- examples/README.md
The existing README was targeted for `connect-sdk`, updated it for `wormhole-sdk-ts`
> fix: update examples readme

- connect/src/routes/cctp/manual.ts
The mintRecipient is the ATA which we were incorrectly passing to the redeem method. Pass the sender instead.
> connect: solana cctp redeem fix

- core/base/src/constants/tokens/index.ts
This ensures a stack trace accompanies the error thrown, improving devex.
> fix: throws an `Error` object instead of plain string in `getTokenMap`

- connect/src/index.ts
- connect/src/protocols/cctp/cctpTransfer.ts
- connect/src/protocols/tokenBridge/tokenTransfer.ts
- connect/src/routes/portico/automatic.ts
- connect/src/routes/request.ts
- connect/src/routes/types.ts
- connect/src/types.ts
- connect/src/warnings.ts
- connect/src/whscan-api.ts
- connect/src/wormhole.ts
- core/base/src/constants/finality.ts
The InReview transfer state is currently set when a token bridge transfer is enqueued in the Governor.
Added Governor warnings to token bridge quotes.
Fixed an issue where the token price wasn't being looked up by its origin chain.
> connect: Added InReview transfer state, governor warnings and fixes

- connect/src/protocols/cctp/cctpTransfer.ts
- connect/src/routes/cctp/automatic.ts
- core/definitions/src/protocols/circleBridge/circleBridge.ts
- platforms/evm/protocols/cctp/src/automaticCircleBridge.ts
- use wormhole circle relayer instead of token bridge relayer to compute max swap and gas drop-off amounts
- the connect interface specifies a percentage that is applied to the the max swap amount to get the gas drop-off amount
> cctp: gas drop-off fix

- connect/src/protocols/tokenBridge/tokenTransfer.ts
- connect/src/wormhole.ts
- core/definitions/src/protocols/tokenBridge/tokenBridge.ts
- core/definitions/src/testing/mocks/tokenBridge.ts
- platforms/algorand/protocols/tokenBridge/src/tokenBridge.ts
- platforms/algorand/src/address.ts
- platforms/aptos/protocols/tokenBridge/src/tokenBridge.ts
- platforms/cosmwasm/protocols/tokenBridge/src/tokenBridge.ts
- platforms/cosmwasm/src/gateway.ts
- platforms/evm/protocols/tokenBridge/src/tokenBridge.ts
- platforms/solana/protocols/tokenBridge/src/tokenBridge.ts
- platforms/sui/protocols/tokenBridge/src/tokenBridge.ts
- Added getTokenUniversalAddress and getTokenNativeAddress methods to each platform's token bridge protocol implementation.
- Some chains like Aptos and Sui require fetching on-chain data for token address conversions (universal to native and vice versa).
- Fixed issue where lookupDestinationToken would return a universal address, causing issues in functions expecting a native address.
- lookupDestinationToken now consistently returns a native address.
- Resolved issues with transferring native Sui and Aptos tokens back to their origin chains.
> tokenBridge protocol: add token address conversion methods

- connect/src/protocols/cctp/cctpTransfer.ts
- connect/src/routes/portico/automatic.ts
- connect/src/wormhole.ts
We were not passing the config, which may contain overrides, to the platform constructors in the Wormhole class. This was causing the default RPCs to get used even if they were overridden in the config.
> connect: Wormhole pass config to platform constructors

- connect/src/routes/cctp/automatic.ts
- connect/src/routes/portico/automatic.ts
- connect/src/routes/route.ts
- connect/src/routes/tokenBridge/automatic.ts
These should have been static to begin with. This change lets us reference them on the route constructor, before the route has been initialized. Helpful to clean up [this](https://github.com/wormhole-foundation/wormhole-connect/blob/development/wormhole-connect/src/routes/sdkv2/route.ts#L51-L64) where we don't have an instance of the route, only the constructor.
> Make IS_AUTOMATIC & NATIVE_GAS_DROPOFF_SUPPORTED into static properties

- core/base/src/constants/contracts/core.ts
- core/base/src/constants/contracts/relayer.ts
- core/base/src/constants/contracts/tokenBridge.ts
- core/base/src/constants/nativeChainIds.ts
This PR enables Snaxchain mainnet support. It also updates the testnet deployment since they changed the EVM chain ID for it.
The mainnet contracts are here:
- [Core bridge](https://explorer.snaxchain.io/address/0xc1BA3CC4bFE724A08FbbFbF64F8db196738665f4)
- [Token bridge](https://explorer.snaxchain.io/address/0x8B94bfE456B48a6025b92E11Be393BAa86e68410)
- [Automatic relayer](https://explorer.snaxchain.io/address/0x27428DD2d3DD32A4D7f7C497eAaa23130d894911)
The testnet contracts are here:
- [Core bridge](https://testnet-explorer.snaxchain.io/address/0xBB73cB66C26740F31d1FabDC6b7A46a038A300dd)
- [Token bridge](https://testnet-explorer.snaxchain.io/address/0xa10f2eF61dE1f19f586ab8B6F2EbA89bACE63F7a)
> Add Snaxchain mainnet support

- connect/src/routes/tokenBridge/automatic.ts
- connect/src/routes/types.ts
This should be used to communicate that `validate()` or `quote()` have failed, but only because the user's transfer amount was too small. UI should use this to show a helpful error so the user can increase their transfer size.
> Custom error class for minimum amount error

- core/base/src/constants/finality.ts
There were two entries for Scroll and Mantle in the finality configurations, so this just removes the duplicates.
> Remove duplicate finality configs

- connect/src/protocols/tokenBridge/tokenTransfer.ts
We were not scaling the transfer amount on the VAA to the source chain amount correctly.
Fixes #580
> tokenBridge: fromIdentifier amount scaling fix

- platforms/solana/src/utils/utils/bpfLoaderUpgradeable.ts
I messed up with [the previous PR](https://github.com/wormhole-foundation/wormhole-sdk-ts/pull/685). I thought the NTT implementation was the correct/latest version but actually it wasn't... this one is.
> fix wrong bpfUpgradeableLoader layout

- platforms/solana/src/platform.ts
In LibertAI token NTT integration we saw this bug in Solana token selector:
It shows as disabled when I have a balance in my wallet. It happens because the LibertAI token uses the program [spl token 2022](https://github.com/solana-labs/solana-program-library/blob/21f0430147686d2a948e090b358b1fbfe2d4bb03/token/js/src/constants.ts#L7), and the SDK only queries the spl token program https://github.com/wormhole-foundation/wormhole-sdk-ts/blob/main/platforms/solana/src/platform.ts#L153-L158.
The solution we found is to include request with the spl token 2022 program id https://github.com/solana-labs/solana-program-library/blob/master/token/js/src/constants.ts#L7
> Include Spl Token 2022 in getBalances

- core/base/__tests__/finality.ts
- core/base/src/constants/finality.ts
finality is somewhere between 64 and 95 blocks
> use 72 blocks for eth finality which should cover p75

- core/base/src/constants/contracts/core.ts
The core contract is now available [here](https://brightstar-884.devnet1.monad.xyz/address/0xBB73cB66C26740F31d1FabDC6b7A46a038A300dd).
> Update Monad devnet core address

- core/base/src/constants/guardians.ts
- core/base/src/utils/array.ts
- core/base/src/utils/mapping.ts
- core/base/src/utils/metaprogramming.ts
The branch name is outdated. Initially intended to only add the one function that I needed, but then realized various issues in the code (primarily the usage of RoArray, when Tuple types were expected and "generic" RoArray that were not tuples under the hood actually produced incorrect results).
Types are now handled more appropriately and robustly.
e.g.
```
const arr = [[1,2], [3,4]];
const zipped = zip(arr); //previously had type never[], now has type RoArray2D<number>
```
The main downside is that compile time has gone up significantly (by 15 seconds, from 55s to 70s on my machine).
> fix, cleanup, and tighten type programming utils

- connect/src/routes/resolver.ts
If a route fails to properly check the chains in `supportedDestinationTokens` as [the Mayan route does right now (oops)](https://github.com/mayan-finance/wormhole-sdk-route/blob/main/src/index.ts#L122) then this will be a helpful fallback.
> Make sure both chains are supported

- platforms/solana/src/platform.ts
This function has a bug: it accepts type `AnySolanaAddress[]` where `AnySolanaAddress` is either a Solana `NativeAddress` or a [`PublicKeyInitData` from web3.js](https://solana-labs.github.io/solana-web3.js/v1.x/types/PublicKeyInitData.html) which can be a string... but then it assumes it's working with a string in this equality check because the RPC response `account.data.parsed?.info?.mint` is a string.
This change ensures that we are indeed comparing a string to a string.
> Ensure token address is a string

- platforms/evm/src/signer.ts
The EVM signer's gas limit is hardcoded to 500,000, which is insufficient for chains like Arbitrum in some cases. 
- Failed with 50w gas, https://arbiscan.io/tx/0xa52ff890d9e43ba316c43fb357800bed0b7b59ef9f3143b1514f4a8b79812f5e
- Extremely high with 51,881,506 gas  https://arbiscan.io/tx/0xe3fa9f5201a3c9b1fe3d709e3add4b17a633639d5b8f280f9c05c4e6cef2a192
We need to provide the ability to modify the gas limit in EvmSignerOptions.
Dune query:
`
select *
from arbitrum.transactions
where to = 0x0b2402144Bb366A632D14B83F244D2e0e21bD39c
order by gas_used desc
limit 100
`
> Add gasLimit option to EvmSignerOptions for overriding gas limit

- package-lock.json
- platforms/aptos/__tests__/integration/tokenBridge.test.ts
- platforms/aptos/__tests__/unit/platform.test.ts
- platforms/aptos/package.json
- platforms/aptos/protocols/core/src/core.ts
- platforms/aptos/protocols/tokenBridge/src/tokenBridge.ts
- platforms/aptos/protocols/tokenBridge/src/types.ts
- platforms/aptos/src/platform.ts
- platforms/aptos/src/signer.ts
- platforms/aptos/src/unsignedTransaction.ts
use @aptos-labs/ts-sdk instead of deprecated aptos package
> aptos: migrate sdk to latest version

- core/base/src/constants/rpc.ts
Goerli testnet is deprecated, and the URL no longer works. This change updates the testnet RPC endpoint to the sepolia testnet
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/wormhole-foundation/wormhole-sdk-ts/pull/783?shareId=193f2ebe-0bb2-49a1-8847-6425ed9164b3).
> Update ETH testnet to sepolia from goerli

- core/base/src/utils/array.ts
- core/base/src/utils/misc.ts
- platforms/solana/src/signer.ts
Added determinePriorityFeeTritonOne function
> Added Triton One improved priority fee API support

- core/base/src/constants/contracts/core.ts
- core/base/src/constants/contracts/tokenBridge.ts
- core/base/src/constants/nativeChainIds.ts
- core/base/src/constants/rpc.ts
The core is available [here](https://unichain-d7a86fxp.blockscout.com/address/0xCa1D5a146B03f6303baF59e5AD5615ae0b9d146D).
The token bridge is available [here](https://unichain-d7a86fxp.blockscout.com/address/0x3Ff72741fd67D6AD0668d93B41a09248F4700560).
> Add Unichain mainnet support

- core/base/src/constants/contracts/core.ts
- core/base/src/constants/contracts/tokenBridge.ts
- core/base/src/constants/nativeChainIds.ts
- core/base/src/constants/rpc.ts
The core is available [here](https://berascan.com/address/0xCa1D5a146B03f6303baF59e5AD5615ae0b9d146D).
The token bridge is available [here](https://berascan.com/address/0x3Ff72741fd67D6AD0668d93B41a09248F4700560).
> Add Berachain mainnet support

- core/base/src/constants/nativeChainIds.ts
- core/base/src/constants/rpc.ts
Berachain has redeployed their testnet to Bepolia. Although this didn't change the contract addresses, it did change the EVM chain ID. This PR updates that.
- The core is available [here](https://bepolia.beratrail.io/address/0xBB73cB66C26740F31d1FabDC6b7A46a038A300dd).
- The token bridge is available [here](https://bepolia.beratrail.io/address/0xa10f2eF61dE1f19f586ab8B6F2EbA89bACE63F7a).
Note that the explorer labels the core as a token bridge, but if you look at the "Read as Proxy" tab, you will see it is really the core.
> Update Berachain testnet

- core/base/src/constants/rpc.ts
old bsc RPC returned following error:
> server response 401 Unauthorized (request={  }, response={  }, error=null, info={ "requestUrl": "https://bscrpc.com", "responseBody": "{\"error\":\"message: API key disabled, json-rpc code: -32051, rest code: 403\"}", "responseStatus": "401 Unauthorized" }
> update bsc rpc on mainnet

- connect/src/protocols/cctp/cctpTransfer.ts
- connect/src/protocols/tokenBridge/tokenTransfer.ts
- connect/src/routes/portico/automatic.ts
- connect/src/routes/request.ts
- connect/src/routes/tbtc/tbtc.ts
- connect/src/routes/types.ts
- connect/src/types.ts
- core/base/__tests__/time.ts
- core/base/src/utils/index.ts
- core/base/src/utils/time.ts
- expose how long a quote is good for
- set to 5 minutes for relayed routes
- set to 24 hours for manual routes (which technically never expire)
> Add expiration time to `Quote`

- connect/src/routes/request.ts
Useful for routes that need the recipient address for quoting more accurately
> Added optional recipient address to RouteTransferRequest

- connect/src/routes/tbtc/README.md
Replaced the outdated link to the L2WormholeGateway.sol source file with the current official documentation link in the tBTC route README. This ensures users have access to up-to-date information about the contract and its functionality.
> Update L2WormholeGateway contract link in tBTC route README

- core/definitions/src/protocols/governance/layout.ts
- platforms/evm/protocols/cctp/src/circleBridge.ts
- platforms/solana/protocols/cctp/src/anchor-idl/messageTransmitter.ts
- platforms/solana/protocols/cctp/src/circleBridge.ts
Fixed typo Messenge → Messenger in error message string in both EVM and Solana circleBridge.ts.
Fixed typo resused → reused in documentation comments of messageTransmitter.ts (Anchor IDL).
These changes improve clarity and consistency in error reporting and documentation.
> fix: correct typos in Circle Messenger error and documentation strings

- core/base/src/constants/circle.ts
Add USDC contract addresses for HyperEVM to support CCTP executor routes.
- Added HyperEVM USDC contract address for Mainnet: `0xb88339CB7199b77E23DB6E890353E22632Ba630f`
- Added HyperEVM USDC contract address for Testnet: `0x2B3370eE501B4a559b57D449569354196457D8Ab`
HyperEVM will be supported via CCTPv2 executor routes. These addresses are required for the executor to facilitate USDC transfers to/from HyperEVM.
> Add HyperEVM USDC contract address

- core/base/src/constants/circle.ts
- Add mainnet USDC contract address for Plume chain (0x222365EF19F7947e5484218551B56bb3965Aa7aF)
> feat: Add Plume USDC contract address

- core/base/src/constants/explorer.ts
- Adds mainnet Ink explorer configuration at https://explorer.inkonchain.com/
- Adds testnet (Sepolia) Ink explorer configuration at https://explorer-sepolia.inkonchain.com/
This completes the Ink chain integration in the SDK by adding the missing explorer endpoints.
> feat: add Ink explorer configuration
